# generated by gdp new: https://gdp.baidu-int.com/gdp3/docs/quickstart/gdp/
# 初始化项目目录变量
HOMEDIR := $(shell pwd)
OUTDIR  := $(HOMEDIR)/output

# 应用名称/二进制文件名称
APPNAME = managed-agent-mvp

GOPKGS  := $$(go list ./...| grep -vE "vendor")

# 设置编译时所需要的 Go 环境
export GOENV = $(HOMEDIR)/go.env

#执行编译，可使用命令 make 或 make all 执行， 顺序执行 prepare -> compile -> test -> package 几个阶段
all: prepare compile test package

# prepare阶段， 使用 bcloud 下载非 Go 依赖，可单独执行命令: make prepare
prepare:
	#bcloud local -U # 下载非 Go 依赖，依赖 BCLOUD 文件
	git version     # 低于 2.17.1 可能不能正常工作
	go env          # 打印出 go 环境信息，可用于排查问题
	go mod download || go mod download -x # 下载 Go 依赖

# compile 阶段，执行编译命令，可单独执行命令: make compile
compile:build
build: prepare
	go build -o $(HOMEDIR)/bin/$(APPNAME)
	#bash cmd/build.sh

# test 阶段，进行单元测试， 可单独执行命令: make test
# cover 平台会优先执行此命令
test: prepare
	go test -race -timeout=300s -v -cover $(GOPKGS) -coverprofile=coverage.out | tee unittest.txt

# package 阶段，对编译产出进行打包，输出到 output 目录， 可单独执行命令: make package
package:
	$(shell rm -rf $(OUTDIR))
	$(shell mkdir -p $(OUTDIR))
	$(shell mkdir -p $(OUTDIR)/var/)
	$(shell cp -a bin $(OUTDIR)/bin)
	$(shell cp -a conf_online $(OUTDIR)/conf)
	$(shell if [ -d "data_online" ]; then cp -r data_online $(OUTDIR)/data; fi)
	$(shell if [ -d "script" ]; then cp -r script $(OUTDIR)/script; fi)
	$(shell if [ -d "webroot" ]; then cp -r webroot $(OUTDIR)/; fi)
	$(shell if [ -d "noahdes" ]; then cp -r noahdes $(OUTDIR)/; fi)
	$(shell mkdir -p $(OUTDIR)/exiftool/)
	$(shell wget -P $(OUTDIR)/exiftool/ https://xy-character-pub.cdn.bcebos.com/online/aisuda/2025-08/Image-ExifTool-13.33.tar.gz)
	$(shell tar -xzf $(OUTDIR)/exiftool/Image-ExifTool-13.33.tar.gz -C $(OUTDIR)/exiftool --strip-components=1 2>/dev/null)
	$(shell rm $(OUTDIR)/exiftool/Image-ExifTool-13.33.tar.gz)
	tree $(OUTDIR)

# clean 阶段，清除过程中的输出， 可单独执行命令: make clean
clean:
	rm -rf $(OUTDIR)

# avoid filename conflict and speed up build
.PHONY: all prepare compile test package  clean build
